version: '3.5'

services:
  php:
    build:
      context: ./docker/php
    container_name: sfproject_php
    volumes:
      - .:/var/www/html:delegated
      - ../../.composer:/var/www/.composer
    working_dir: /var/www/html

  nginx:
    image: nginx:1.11.10
    container_name: sfproject_nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mariadb:
    image: mariadb:10.5.5
    command: 'mysqld --innodb-flush-method=fsync' # --innodb-use-native-aio=0
    restart: always
    container_name: sfproject_mariadb
    environment:
      - MYSQL_DATABASE=api_course
      - MYSQL_USER=davidmaarek
      - MYSQL_PASSWORD=davidmaarek
      - MYSQL_ROOT_PASSWORD=davidmaarek
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/var/lib/mysql
